// app/layout.tsx (example)
import { ThemeProvider } from "@/components/theme-provider"
import ModernNavbar from '@/components/Navbar'; // Adjust path
import './globals.css';

export const metadata = {
  title: 'My Modern App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModernNavbar />
          <main className="pt-24"> {/* Add padding to offset fixed navbar */}
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}